### ISSUE TITLE
Bug with spotted horses?

### ISSUE THREAD

**Issue by Shark00011001** [Kiddooo/HorseInfo#1]
![Screen Shot 2024-09-29 at 2 38 12 PM](https://github.com/user-attachments/assets/2e4bff0c-3be9-47a0-8e0c-1e37771beb58)
This is Wilson, and he can't have his statistics checked :(
![Screen Shot 2024-09-29 at 2 44 24 PM](https://github.com/user-attachments/assets/d2b24a80-8b12-4d19-b6b5-010dfaf73f27)
This horse also can't have her statistics checked.
Afaik all other patterns workkk i think it could be an issue with splotched horse?
((i really like this mod btw!! i've been finding it super useful :D))

**Comment by Kiddooo** [comment]
Hi there! Thank you for the bug report completely overlooked this during testing. 
This has been fixed in 1.3! You can get it [here](https://modrinth.com/mod/horse-info/version/1.3)

It was an issue with the `whitefield` identifier being named `whitefield` and not `white_field`

I'm glad you like the mod :)
